### ISSUE TITLE
Crashes with Underscore V 1.8.3

### ISSUE THREAD

**Issue by i-am-al-x** [dperrymorrow/example-backbone-app#2]
The program crashes with a "Referenc Error" when I use the 1.8.3 version of "underscore.js".

Crashes with the following:

<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.3/zepto.min.js"></script>

<script type="text/javascript" src="vendor/underscore.js"></script>

<script type="text/javascript" src="vendor/backbone.js"></script>

But does not crash with this:

<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.3/zepto.min.js"></script>

<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>

<script type="text/javascript" src="vendor/backbone.js"></script>
 

The error message is:

```
ReferenceError: id is not defined
```

The crash is actually happening in an anonymous function that is attempting to expand a template.  The function is apparently expecting a "model" to appear within a member named "obj"; but instead it is being passed the index of an array; that value is the integer zero '0'.  The "this" value is "<tr>".

The problem can be examined easily in Firebug by using the configuration described above, and putting a single break point at:

```
note_row.js  line 20
   this.$el.html(_.template($('#rowTemplate').html(), this.note.toJSON()));
```

Upon stopping there, step into a few lines of execution, and the error occurs.

The following anonymous function and stack were produced as described above.

var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
with(obj||{}){
__p+='\n    <td>\n      <a href="#note/'+
((__t=( id ))==null?'':__t)+
'/view">'+
((__t=( title ))==null?'':__t)+
'</a>\n    </td>\n    <td>'+
((__t=( author ))==null?'':__t)+
'</td>\n    <td>';
 print(description.substring(0, 100)) 
__p+='...</td>\n    <td>\n      <a href="#" class="delete btn btn-danger btn-small">delete</a>\n    </td>\n  ';
}
return __p;

anonymous()                     underscore.js line 1454 > Function:4
_.template/template()           underscore.js:1461
J()                                        zepto.min.js:2
Zepto</n.fn.html/<()               zepto.min.js:2
Zepto</n.fn.each/<()               zepto.min.js:2
every()                                     self-hosted:163
Zepto</n.fn.each()                  zepto.min.js:2
Zepto</n.fn.html()                    zepto.min.js:2
APP.NoteRowView<.render()           note_row.js:20
APP.NoteIndexView<.addOne()          note_index.js:29
t.proxy/i()                                zepto.min.js:2
_.forEach()                              underscore.js:153
APP.NoteIndexView<.addAll()           note_index.js:21
triggerEvents()                         backbone.js:368
triggerApi()                                backbone.js:354
eventsApi()                               backbone.js:153
Events.trigger()                         backbone.js:344
.reset()                                      backbone.js:933
<anonymous>                           index.html:146

**Comment by dperrymorrow** [comment]
thanks, haven't tried with a newer underscore. the way templates work has changed a little bit. 
Have updated.
